name: Build SFTP Server
on: 
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install musl-tools
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build sfpt-server
        run: cd sftp-server && ./compile.sh

      - name: Compress artifacts
        run: tar -czvf artifacts.tar.gz sftp-server/sftp-server

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./sftp-server/sftp-server

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref_name}}  artifacts.tar.gz -R https://github.com/pigfall/tmp-releases.git
