name: Build SFTP Server
on: 
  push:
    paths:
      - 'sftp-server/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install musl-tools
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build sfpt-server
        run: cd sftp-server && ./compile.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./sftp-server/sftp-server
