on: 
  push:
    tags:
      - "v*.*.*"


jobs:
  create-release:
    name: Create Release
    needs: [build-sftp-server]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Compress artifacts
        run: tar -czvf artifacts.tar.gz artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./sftp-server/sftp-server

      - name: Publish To Dedicated Repo
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW }}
        run: |
          gh release create ${{github.ref_name}}  artifacts.tar.gz -R https://github.com/pigfall/tmp-releases.git

  build-sftp-server:
    name: Build SFTP Server
    runs-on: ubuntu-latest
    steps:
      - name: Install musl-tools
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build sfpt-server
        run: cd sftp-server && ./compile.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sftp-server-name
          path: sftp-server/sftp-server
          retention-days: 1
